2024-11-01 12:01:54,797 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\terektat\OneDrive - Mars Inc\Desktop\tt\Local my\Urban Python 2024\HW_Modul_12_UnitTests\HW_module_12\tests_12_4.py", line 14, in test_run
    r1 = Runner(True,5)
         ^^^^^^^^^^^^^^
  File "C:\Users\terektat\OneDrive - Mars Inc\Desktop\tt\Local my\Urban Python 2024\HW_Modul_12_UnitTests\HW_module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-11-01 12:01:54,798 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\terektat\OneDrive - Mars Inc\Desktop\tt\Local my\Urban Python 2024\HW_Modul_12_UnitTests\HW_module_12\tests_12_4.py", line 24, in test_walk
    w1 = Runner("Tanya", -5)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\terektat\OneDrive - Mars Inc\Desktop\tt\Local my\Urban Python 2024\HW_Modul_12_UnitTests\HW_module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
